### ISSUE TITLE
Crysis 1 and 2

### ISSUE THREAD

**Issue by ganhailin** [ptitSeb/box86-compatibility-list#78]
### Description
around 5 fps with crysis2 and 15fps playable with crysis 1 
crysis 1 runs with native dx9 dlls (install with winetrick and -dx9 args),crack version 
crysis 2 runs with builtin dx10, crack version too.

### Tested on
wine in box86 in armhf multiarch libs in ubuntu20.04 aarch64 server version in qemu-system-aarch64 with kvm mode and virglrenderer in Jetson AGX with kvm enabled kernel

### Status
**Previous behavior:** 
None reported

**Current behavior:**
runing.

**Comment by bbbruni** [comment]
> version in qemu-system-aarch64 with kvm
That slowed the game at least by half.

**Comment by ptitSeb** [comment]
Can you create 1 ticket for each Crysis, and put an actual screenshot from it running on you arm sbc please?

**Comment by Firlaev-Hans** [comment]
> wine in box86 in armhf multiarch libs in ubuntu20.04 aarch64 server version in qemu-system-aarch64 with kvm mode and virglrenderer in Jetson AGX with kvm enabled kernel

Interesting, could you explain how you
a) got a kvm enabled kernel on the Jetson and
b) got virtio / virgl graphics to work with `qemu-system-aarch64`? Maybe just paste the command you used to run QEMU that way.

This sounds like a fun way to work around the 64 Bit only graphics driver limitation on NVIDIA Tegra based computers that otherwise can't run 32 Bit games, but I got neither KVM nor any graphics in QEMU to work.

**Comment by rajdakin** [comment]
Closing due to multiple years of not complying to the request (split this in two issues with screenshots).
